### PR TITLE
Support for unicode normalisation to ASCII

### PR DESCRIPTION
**Pull request by grafana-dee**
Now if you send in a rune like ü it would be translated to a u.
This means a larger alphabet will converted to Slack alphabet chars

### CODE REVIEW

**Comment by RichiH** [comment]
Please consider switching from DIN 5007-1 variant 1 to DIN 5007-1 variant 2 for the purpose of converting into ISO/IEC 8859-1.

**Comment by grafana-dee** [comment]
That would require changes to the unicode spec https://unicode.org/reports/tr15/ and https://unicode.org/notes/tn5/ which is beyond the scope of this PR :grinning:

**Comment by RichiH** [comment]
ISO/IEC 8859 is the direct successor of ISO 646. ISO/IEC 10646 extends ISO/IEC 8859.

As to the matter of following ISO/IEC 10646 over DIN 5007-1, I would argue that the native speakers should be the reference for proper use of their language.

**Review by rfratto — APPROVED** [review]
LGTM!

**Comment by RichiH** [comment]
The standards bodies...! They are weeping!

**Pull request merged**
